name: RN3
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.2=h0a44026_0
  - openssl=1.1.1d=h1de35cc_4
  - pip=20.0.2=py38_1
  - python=3.8.1=h359304d_1
  - readline=7.0=h1de35cc_5
  - setuptools=46.0.0=py38_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - numpy==1.18.1
    - opencv-python==4.2.0.32
    - torch==1.4.0
prefix: /Users/davidspeck/miniconda3/envs/RN3

